// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_fdd8092855022054e9c339b99ce2323a_6a2f12a25cae4b77a9de508896d78217 : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_fdd8092855022054e9c339b99ce2323a_5e6e806b31274770bceacede4f916996 : IntBinding
    {   
        private global::SkeletonEntity CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::SkeletonEntity)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_fdd8092855022054e9c339b99ce2323a_884555094444823638);
        public override string CoherenceComponentName => "_fdd8092855022054e9c339b99ce2323a_884555094444823638";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Int32 Value
        {
            get { return (System.Int32)(CastedUnityComponent.Health); }
            set { CastedUnityComponent.Health = (System.Int32)(value); }
        }

        protected override (System.Int32 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_fdd8092855022054e9c339b99ce2323a_884555094444823638)coherenceComponent).Health;

            var simFrame = ((_fdd8092855022054e9c339b99ce2323a_884555094444823638)coherenceComponent).HealthSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_fdd8092855022054e9c339b99ce2323a_884555094444823638)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Health = Value;
            }
            else
            {
                update.Health = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.HealthSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _fdd8092855022054e9c339b99ce2323a_884555094444823638();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_fdd8092855022054e9c339b99ce2323a_6e8731824b6349deb4ba85ae85fe20dc : BoolBinding
    {   
        private global::UnityEngine.SpriteRenderer CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.SpriteRenderer)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_fdd8092855022054e9c339b99ce2323a_4530313596208706395);
        public override string CoherenceComponentName => "_fdd8092855022054e9c339b99ce2323a_4530313596208706395";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Boolean Value
        {
            get { return (System.Boolean)(CastedUnityComponent.flipX); }
            set { CastedUnityComponent.flipX = (System.Boolean)(value); }
        }

        protected override (System.Boolean value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_fdd8092855022054e9c339b99ce2323a_4530313596208706395)coherenceComponent).flipX;

            var simFrame = ((_fdd8092855022054e9c339b99ce2323a_4530313596208706395)coherenceComponent).flipXSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_fdd8092855022054e9c339b99ce2323a_4530313596208706395)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.flipX = Value;
            }
            else
            {
                update.flipX = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.flipXSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _fdd8092855022054e9c339b99ce2323a_4530313596208706395();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_fdd8092855022054e9c339b99ce2323a_3dffe206089e473d90f059d0dbbc89f8 : FloatBinding
    {   
        private global::UnityEngine.Animator CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Animator)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_fdd8092855022054e9c339b99ce2323a_2811260201814078637);
        public override string CoherenceComponentName => "_fdd8092855022054e9c339b99ce2323a_2811260201814078637";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.speed); }
            set { CastedUnityComponent.speed = (System.Single)(value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_fdd8092855022054e9c339b99ce2323a_2811260201814078637)coherenceComponent).speed;

            var simFrame = ((_fdd8092855022054e9c339b99ce2323a_2811260201814078637)coherenceComponent).speedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_fdd8092855022054e9c339b99ce2323a_2811260201814078637)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.speed = Value;
            }
            else
            {
                update.speed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.speedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _fdd8092855022054e9c339b99ce2323a_2811260201814078637();
        }    
    }
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_fdd8092855022054e9c339b99ce2323a_cb93e793d96e4c1982f0ddcbf7fe6b88 : FloatBinding
    {   
        private global::FollowGameObject CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::FollowGameObject)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(_fdd8092855022054e9c339b99ce2323a_5729286325588990472);
        public override string CoherenceComponentName => "_fdd8092855022054e9c339b99ce2323a_5729286325588990472";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override System.Single Value
        {
            get { return (System.Single)(CastedUnityComponent.Speed); }
            set { CastedUnityComponent.Speed = (System.Single)(value); }
        }

        protected override (System.Single value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((_fdd8092855022054e9c339b99ce2323a_5729286325588990472)coherenceComponent).Speed;

            var simFrame = ((_fdd8092855022054e9c339b99ce2323a_5729286325588990472)coherenceComponent).SpeedSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (_fdd8092855022054e9c339b99ce2323a_5729286325588990472)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.Speed = Value;
            }
            else
            {
                update.Speed = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.SpeedSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new _fdd8092855022054e9c339b99ce2323a_5729286325588990472();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_fdd8092855022054e9c339b99ce2323a : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_fdd8092855022054e9c339b99ce2323a>();
        
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["6a2f12a25cae4b77a9de508896d78217"] = new Binding_fdd8092855022054e9c339b99ce2323a_6a2f12a25cae4b77a9de508896d78217(),
			["5e6e806b31274770bceacede4f916996"] = new Binding_fdd8092855022054e9c339b99ce2323a_5e6e806b31274770bceacede4f916996(),
			["6e8731824b6349deb4ba85ae85fe20dc"] = new Binding_fdd8092855022054e9c339b99ce2323a_6e8731824b6349deb4ba85ae85fe20dc(),
			["3dffe206089e473d90f059d0dbbc89f8"] = new Binding_fdd8092855022054e9c339b99ce2323a_3dffe206089e473d90f059d0dbbc89f8(),
			["cb93e793d96e4c1982f0ddcbf7fe6b88"] = new Binding_fdd8092855022054e9c339b99ce2323a_cb93e793d96e4c1982f0ddcbf7fe6b88(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_fdd8092855022054e9c339b99ce2323a()
        {
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_fdd8092855022054e9c339b99ce2323a Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_fdd8092855022054e9c339b99ce2323a>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
