// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve, System.Serializable]
    public class Binding_a55cf70594cc67b49954c6086f44af79_da30d5689ccd4adf988fa2abcb1f397e : PositionBinding
    {   
        private global::UnityEngine.Transform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.Transform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_a55cf70594cc67b49954c6086f44af79 : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_a55cf70594cc67b49954c6086f44af79>();
        
        private global::GameManager _a55cf70594cc67b49954c6086f44af79_d94ea1d17cf745ee8dbdcc21cb00b6e1_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["da30d5689ccd4adf988fa2abcb1f397e"] = new Binding_a55cf70594cc67b49954c6086f44af79_da30d5689ccd4adf988fa2abcb1f397e(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_a55cf70594cc67b49954c6086f44af79()
        {
            bakedCommandBindings.Add("d94ea1d17cf745ee8dbdcc21cb00b6e1", BakeCommandBinding__a55cf70594cc67b49954c6086f44af79_d94ea1d17cf745ee8dbdcc21cb00b6e1);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__a55cf70594cc67b49954c6086f44af79_d94ea1d17cf745ee8dbdcc21cb00b6e1(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _a55cf70594cc67b49954c6086f44af79_d94ea1d17cf745ee8dbdcc21cb00b6e1_CommandTarget = (global::GameManager)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"GameManager.RestartClient",
            	"()",
            	SendCommand__a55cf70594cc67b49954c6086f44af79_d94ea1d17cf745ee8dbdcc21cb00b6e1,
            	ReceiveLocalCommand__a55cf70594cc67b49954c6086f44af79_d94ea1d17cf745ee8dbdcc21cb00b6e1,
            	MessageTarget.All,
            	_a55cf70594cc67b49954c6086f44af79_d94ea1d17cf745ee8dbdcc21cb00b6e1_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__a55cf70594cc67b49954c6086f44af79_d94ea1d17cf745ee8dbdcc21cb00b6e1(GenericCommandRequestArgs requestArgs)
        {
            var command = new _a55cf70594cc67b49954c6086f44af79_d94ea1d17cf745ee8dbdcc21cb00b6e1();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__a55cf70594cc67b49954c6086f44af79_d94ea1d17cf745ee8dbdcc21cb00b6e1(GenericCommandRequestArgs requestArgs)
        {
            var command = new _a55cf70594cc67b49954c6086f44af79_d94ea1d17cf745ee8dbdcc21cb00b6e1();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;


            ReceiveCommand__a55cf70594cc67b49954c6086f44af79_d94ea1d17cf745ee8dbdcc21cb00b6e1(command);
        }

        private void ReceiveCommand__a55cf70594cc67b49954c6086f44af79_d94ea1d17cf745ee8dbdcc21cb00b6e1(_a55cf70594cc67b49954c6086f44af79_d94ea1d17cf745ee8dbdcc21cb00b6e1 command)
        {
            var target = _a55cf70594cc67b49954c6086f44af79_d94ea1d17cf745ee8dbdcc21cb00b6e1_CommandTarget;
			target.RestartClient();
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _a55cf70594cc67b49954c6086f44af79_d94ea1d17cf745ee8dbdcc21cb00b6e1 castedCommand:
                    ReceiveCommand__a55cf70594cc67b49954c6086f44af79_d94ea1d17cf745ee8dbdcc21cb00b6e1(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_a55cf70594cc67b49954c6086f44af79 Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_a55cf70594cc67b49954c6086f44af79>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
